/**
 * Theme palettes — generated by scripts, not hand-picked.
 *
 * Built from the brand palette the owner chose. Every value is
 * solved for a contrast target rather than eyeballed, because hue changes
 * perceived brightness: at equal HSL lightness a yellow reads far lighter than
 * a blue, which is what made an earlier attempt fail WCAG on four of the nine
 * capital axes.
 *
 * Targets: secondary text (ink-500) >= 4.5:1 on the page background,
 * decorative grey (ink-400) >= 3:1, every capital axis >= 4.5:1.
 *
 * ink-50 is the page background and ink-200 is the border colour on purpose —
 * that is what lets existing `bg-ink-50` / `border-ink-200` markup follow the
 * theme without being rewritten.
 */

export type ThemeName = "light" | "dark";

export interface Palette {
  name: ThemeName;
  label: string;
  brand: Record<number, string>;
  ink: Record<number, string>;
  accent: string;
  page: string;
  card: string;
  border: string;
  mode: "light" | "dark";
  /** Text for saturated surfaces. Never assume white or the page colour. */
  onColour: string;
  success: string;
  warning: string;
  danger: string;
  info: string;
  /** Capital axis colours keyed by dimension slug. */
  axes: Record<string, string>;
  /** Ordered categorical scale for charts. */
  chart: string[];
}

export const PALETTES: Record<ThemeName, Palette> = {
  light: {
    name: "light",
    label: "Light",
    brand: {
      50: "#EDE9F5",
      100: "#E3DDF0",
      200: "#D0C5E7",
      300: "#B8A8DC",
      400: "#9B84CD",
      500: "#8164C0",
      600: "#6C4AB6",
      700: "#5D3F9D",
      800: "#4E3583",
      900: "#3F2B6A",
    },
    ink: {
      50: "#F8F7FF",
      100: "#ECE8FA",
      200: "#DBD4F4",
      300: "#C9C2E1",
      400: "#918D99",
      500: "#746F7F",
      600: "#5D5867",
      700: "#4B4754",
      800: "#3E3A46",
      900: "#2F2B35",
    },
    accent: "#FFB86B",
    page: "#F8F7FF",
    card: "#FFFFFF",
    border: "#DBD4F4",
    mode: "light",
    onColour: "#F1F0F3",
    success: "#2B7A53",
    warning: "#90631A",
    danger: "#C03026",
    info: "#7453BD",
    axes: {
      KNOWLEDGE: "#7F5FC2",
      PROFESSIONAL: "#B044B3",
      DIGITAL_AI: "#BA4A72",
      SOCIAL: "#A65F3F",
      ENTREPRENEURIAL: "#76752D",
      FINANCIAL: "#4C7E30",
      PERSONAL_ETHICAL: "#31814A",
      HEALTH: "#2F7C7B",
      CIVIC: "#4970BA",
    },
    chart: [
      "#7F5FC2", "#B044B3", "#BA4A72", "#A65F3F", "#76752D", "#4C7E30", "#31814A", "#2F7C7B", "#4970BA"
    ],
  },
  dark: {
    name: "dark",
    label: "Dark",
    brand: {
      50: "#160E2A",
      100: "#20133E",
      200: "#331D66",
      300: "#4A2798",
      400: "#693DCD",
      500: "#9373DB",
      600: "#B49EE6",
      700: "#BDAAE9",
      800: "#C6B6EC",
      900: "#D0C2EF",
    },
    ink: {
      50: "#2A2634",
      100: "#3B354E",
      200: "#4A4364",
      300: "#726B88",
      400: "#868290",
      500: "#A6A2AF",
      600: "#C4C2CB",
      700: "#DFDEE3",
      800: "#F5F4F6",
      900: "#F7F7F8",
    },
    accent: "#FFB86B",
    page: "#2A2634",
    card: "#3C3650",
    border: "#4A4364",
    mode: "dark",
    onColour: "#1F1C24",
    success: "#3DAF76",
    warning: "#CC9024",
    danger: "#E36255",
    info: "#9672DC",
    axes: {
      KNOWLEDGE: "#AD99D8",
      PROFESSIONAL: "#D18BD3",
      DIGITAL_AI: "#D590A8",
      SOCIAL: "#CE977F",
      ENTREPRENEURIAL: "#AAA841",
      FINANCIAL: "#6EB545",
      PERSONAL_ETHICAL: "#46B969",
      HEALTH: "#44B3B0",
      CIVIC: "#8AA5D3",
    },
    chart: [
      "#AD99D8", "#D18BD3", "#D590A8", "#CE977F", "#AAA841", "#6EB545", "#46B969", "#44B3B0", "#8AA5D3"
    ],
  },
};

export const DEFAULT_THEME: ThemeName = "light";

export const THEME_NAMES = Object.keys(PALETTES) as ThemeName[];
